# Generated by Django 6.0.4 on 2026-05-24 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
