# Generated by Django 6.0.4 on 2026-05-24 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0002_race_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
