# Generated by Django 6.0.4 on 2026-05-21 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('race', '0003_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='details',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='race',
            name='image',
            field=models.ImageField(default='default.png', upload_to='race_pics'),
        ),
    ]
